// App Store storefront 全集（ISO 3166-1 alpha-3）。
// 代码取自 Apple App Store Connect API 的 TerritoryCode 枚举；名称由 Intl.DisplayNames
// 生成（en / zh-Hans，clean 常用名），ANT、XKS 手工补全。
// 下方 ALL_STOREFRONTS 为脚本生成（含 Apple 源数据的重复条目，如 ARE）；
// STOREFRONTS 在其后按 code 去重导出，请勿手改字面量。

export interface Storefront {
	code: string;
	en: string;
	zh: string;
}

const ALL_STOREFRONTS: readonly Storefront[] = [
	{ code: "AFG", en: "Afghanistan", zh: "阿富汗" },
	{ code: "ALB", en: "Albania", zh: "阿尔巴尼亚" },
	{ code: "DZA", en: "Algeria", zh: "阿尔及利亚" },
	{ code: "ASM", en: "American Samoa", zh: "美属萨摩亚" },
	{ code: "AND", en: "Andorra", zh: "安道尔" },
	{ code: "AGO", en: "Angola", zh: "安哥拉" },
	{ code: "AIA", en: "Anguilla", zh: "安圭拉" },
	{ code: "ATG", en: "Antigua & Barbuda", zh: "安提瓜和巴布达" },
	{ code: "ARG", en: "Argentina", zh: "阿根廷" },
	{ code: "ARM", en: "Armenia", zh: "亚美尼亚" },
	{ code: "ABW", en: "Aruba", zh: "阿鲁巴" },
	{ code: "AUS", en: "Australia", zh: "澳大利亚" },
	{ code: "AUT", en: "Austria", zh: "奥地利" },
	{ code: "AZE", en: "Azerbaijan", zh: "阿塞拜疆" },
	{ code: "BHS", en: "Bahamas", zh: "巴哈马" },
	{ code: "BHR", en: "Bahrain", zh: "巴林" },
	{ code: "BGD", en: "Bangladesh", zh: "孟加拉国" },
	{ code: "BRB", en: "Barbados", zh: "巴巴多斯" },
	{ code: "BLR", en: "Belarus", zh: "白俄罗斯" },
	{ code: "BEL", en: "Belgium", zh: "比利时" },
	{ code: "BLZ", en: "Belize", zh: "伯利兹" },
	{ code: "BEN", en: "Benin", zh: "贝宁" },
	{ code: "BMU", en: "Bermuda", zh: "百慕大" },
	{ code: "BTN", en: "Bhutan", zh: "不丹" },
	{ code: "BOL", en: "Bolivia", zh: "玻利维亚" },
	{ code: "BIH", en: "Bosnia & Herzegovina", zh: "波斯尼亚和黑塞哥维那" },
	{ code: "BWA", en: "Botswana", zh: "博茨瓦纳" },
	{ code: "BRA", en: "Brazil", zh: "巴西" },
	{ code: "VGB", en: "British Virgin Islands", zh: "英属维尔京群岛" },
	{ code: "BRN", en: "Brunei", zh: "文莱" },
	{ code: "BGR", en: "Bulgaria", zh: "保加利亚" },
	{ code: "BFA", en: "Burkina Faso", zh: "布基纳法索" },
	{ code: "BDI", en: "Burundi", zh: "布隆迪" },
	{ code: "KHM", en: "Cambodia", zh: "柬埔寨" },
	{ code: "CMR", en: "Cameroon", zh: "喀麦隆" },
	{ code: "CAN", en: "Canada", zh: "加拿大" },
	{ code: "CPV", en: "Cape Verde", zh: "佛得角" },
	{ code: "BES", en: "Caribbean Netherlands", zh: "荷属加勒比区" },
	{ code: "CYM", en: "Cayman Islands", zh: "开曼群岛" },
	{ code: "CAF", en: "Central African Republic", zh: "中非共和国" },
	{ code: "TCD", en: "Chad", zh: "乍得" },
	{ code: "CHL", en: "Chile", zh: "智利" },
	{ code: "CHN", en: "China", zh: "中国" },
	{ code: "CXR", en: "Christmas Island", zh: "圣诞岛" },
	{ code: "COL", en: "Colombia", zh: "哥伦比亚" },
	{ code: "COM", en: "Comoros", zh: "科摩罗" },
	{ code: "COG", en: "Congo - Brazzaville", zh: "刚果（布）" },
	{ code: "COD", en: "Congo - Kinshasa", zh: "刚果（金）" },
	{ code: "COK", en: "Cook Islands", zh: "库克群岛" },
	{ code: "CRI", en: "Costa Rica", zh: "哥斯达黎加" },
	{ code: "CIV", en: "Côte d’Ivoire", zh: "科特迪瓦" },
	{ code: "HRV", en: "Croatia", zh: "克罗地亚" },
	{ code: "CUB", en: "Cuba", zh: "古巴" },
	{ code: "CUW", en: "Curaçao", zh: "库拉索" },
	{ code: "CYP", en: "Cyprus", zh: "塞浦路斯" },
	{ code: "CZE", en: "Czechia", zh: "捷克" },
	{ code: "DNK", en: "Denmark", zh: "丹麦" },
	{ code: "DJI", en: "Djibouti", zh: "吉布提" },
	{ code: "DMA", en: "Dominica", zh: "多米尼克" },
	{ code: "DOM", en: "Dominican Republic", zh: "多米尼加共和国" },
	{ code: "ECU", en: "Ecuador", zh: "厄瓜多尔" },
	{ code: "EGY", en: "Egypt", zh: "埃及" },
	{ code: "SLV", en: "El Salvador", zh: "萨尔瓦多" },
	{ code: "GNQ", en: "Equatorial Guinea", zh: "赤道几内亚" },
	{ code: "ERI", en: "Eritrea", zh: "厄立特里亚" },
	{ code: "EST", en: "Estonia", zh: "爱沙尼亚" },
	{ code: "SWZ", en: "Eswatini", zh: "斯威士兰" },
	{ code: "ETH", en: "Ethiopia", zh: "埃塞俄比亚" },
	{ code: "FLK", en: "Falkland Islands", zh: "福克兰群岛" },
	{ code: "FRO", en: "Faroe Islands", zh: "法罗群岛" },
	{ code: "FJI", en: "Fiji", zh: "斐济" },
	{ code: "FIN", en: "Finland", zh: "芬兰" },
	{ code: "FRA", en: "France", zh: "法国" },
	{ code: "GUF", en: "French Guiana", zh: "法属圭亚那" },
	{ code: "PYF", en: "French Polynesia", zh: "法属波利尼西亚" },
	{ code: "GAB", en: "Gabon", zh: "加蓬" },
	{ code: "GMB", en: "Gambia", zh: "冈比亚" },
	{ code: "GEO", en: "Georgia", zh: "格鲁吉亚" },
	{ code: "DEU", en: "Germany", zh: "德国" },
	{ code: "GHA", en: "Ghana", zh: "加纳" },
	{ code: "GIB", en: "Gibraltar", zh: "直布罗陀" },
	{ code: "GRC", en: "Greece", zh: "希腊" },
	{ code: "GRL", en: "Greenland", zh: "格陵兰" },
	{ code: "GRD", en: "Grenada", zh: "格林纳达" },
	{ code: "GLP", en: "Guadeloupe", zh: "瓜德罗普" },
	{ code: "GUM", en: "Guam", zh: "关岛" },
	{ code: "GTM", en: "Guatemala", zh: "危地马拉" },
	{ code: "GGY", en: "Guernsey", zh: "根西岛" },
	{ code: "GIN", en: "Guinea", zh: "几内亚" },
	{ code: "GNB", en: "Guinea-Bissau", zh: "几内亚比绍" },
	{ code: "GUY", en: "Guyana", zh: "圭亚那" },
	{ code: "HTI", en: "Haiti", zh: "海地" },
	{ code: "HND", en: "Honduras", zh: "洪都拉斯" },
	{ code: "HKG", en: "Hong Kong SAR China", zh: "中国香港特别行政区" },
	{ code: "HUN", en: "Hungary", zh: "匈牙利" },
	{ code: "ISL", en: "Iceland", zh: "冰岛" },
	{ code: "IND", en: "India", zh: "印度" },
	{ code: "IDN", en: "Indonesia", zh: "印度尼西亚" },
	{ code: "IRQ", en: "Iraq", zh: "伊拉克" },
	{ code: "IRL", en: "Ireland", zh: "爱尔兰" },
	{ code: "IMN", en: "Isle of Man", zh: "马恩岛" },
	{ code: "ISR", en: "Israel", zh: "以色列" },
	{ code: "ITA", en: "Italy", zh: "意大利" },
	{ code: "JAM", en: "Jamaica", zh: "牙买加" },
	{ code: "JPN", en: "Japan", zh: "日本" },
	{ code: "JEY", en: "Jersey", zh: "泽西岛" },
	{ code: "JOR", en: "Jordan", zh: "约旦" },
	{ code: "KAZ", en: "Kazakhstan", zh: "哈萨克斯坦" },
	{ code: "KEN", en: "Kenya", zh: "肯尼亚" },
	{ code: "KIR", en: "Kiribati", zh: "基里巴斯" },
	{ code: "XKS", en: "Kosovo", zh: "科索沃" },
	{ code: "KWT", en: "Kuwait", zh: "科威特" },
	{ code: "KGZ", en: "Kyrgyzstan", zh: "吉尔吉斯斯坦" },
	{ code: "LAO", en: "Laos", zh: "老挝" },
	{ code: "LVA", en: "Latvia", zh: "拉脱维亚" },
	{ code: "LBN", en: "Lebanon", zh: "黎巴嫩" },
	{ code: "LSO", en: "Lesotho", zh: "莱索托" },
	{ code: "LBR", en: "Liberia", zh: "利比里亚" },
	{ code: "LBY", en: "Libya", zh: "利比亚" },
	{ code: "LIE", en: "Liechtenstein", zh: "列支敦士登" },
	{ code: "LTU", en: "Lithuania", zh: "立陶宛" },
	{ code: "LUX", en: "Luxembourg", zh: "卢森堡" },
	{ code: "MAC", en: "Macao SAR China", zh: "中国澳门特别行政区" },
	{ code: "MDG", en: "Madagascar", zh: "马达加斯加" },
	{ code: "MWI", en: "Malawi", zh: "马拉维" },
	{ code: "MYS", en: "Malaysia", zh: "马来西亚" },
	{ code: "MDV", en: "Maldives", zh: "马尔代夫" },
	{ code: "MLI", en: "Mali", zh: "马里" },
	{ code: "MLT", en: "Malta", zh: "马耳他" },
	{ code: "MHL", en: "Marshall Islands", zh: "马绍尔群岛" },
	{ code: "MTQ", en: "Martinique", zh: "马提尼克" },
	{ code: "MRT", en: "Mauritania", zh: "毛里塔尼亚" },
	{ code: "MUS", en: "Mauritius", zh: "毛里求斯" },
	{ code: "MYT", en: "Mayotte", zh: "马约特" },
	{ code: "MEX", en: "Mexico", zh: "墨西哥" },
	{ code: "FSM", en: "Micronesia", zh: "密克罗尼西亚" },
	{ code: "MDA", en: "Moldova", zh: "摩尔多瓦" },
	{ code: "MCO", en: "Monaco", zh: "摩纳哥" },
	{ code: "MNG", en: "Mongolia", zh: "蒙古" },
	{ code: "MNE", en: "Montenegro", zh: "黑山" },
	{ code: "MSR", en: "Montserrat", zh: "蒙特塞拉特" },
	{ code: "MAR", en: "Morocco", zh: "摩洛哥" },
	{ code: "MOZ", en: "Mozambique", zh: "莫桑比克" },
	{ code: "MMR", en: "Myanmar (Burma)", zh: "缅甸" },
	{ code: "NAM", en: "Namibia", zh: "纳米比亚" },
	{ code: "NRU", en: "Nauru", zh: "瑙鲁" },
	{ code: "NPL", en: "Nepal", zh: "尼泊尔" },
	{ code: "NLD", en: "Netherlands", zh: "荷兰" },
	{ code: "ANT", en: "Netherlands Antilles", zh: "荷属安的列斯" },
	{ code: "NCL", en: "New Caledonia", zh: "新喀里多尼亚" },
	{ code: "NZL", en: "New Zealand", zh: "新西兰" },
	{ code: "NIC", en: "Nicaragua", zh: "尼加拉瓜" },
	{ code: "NER", en: "Niger", zh: "尼日尔" },
	{ code: "NGA", en: "Nigeria", zh: "尼日利亚" },
	{ code: "NIU", en: "Niue", zh: "纽埃" },
	{ code: "NFK", en: "Norfolk Island", zh: "诺福克岛" },
	{ code: "MKD", en: "North Macedonia", zh: "北马其顿" },
	{ code: "MNP", en: "Northern Mariana Islands", zh: "北马里亚纳群岛" },
	{ code: "NOR", en: "Norway", zh: "挪威" },
	{ code: "OMN", en: "Oman", zh: "阿曼" },
	{ code: "PAK", en: "Pakistan", zh: "巴基斯坦" },
	{ code: "PLW", en: "Palau", zh: "帕劳" },
	{ code: "PSE", en: "Palestinian Territories", zh: "巴勒斯坦领土" },
	{ code: "PAN", en: "Panama", zh: "巴拿马" },
	{ code: "PNG", en: "Papua New Guinea", zh: "巴布亚新几内亚" },
	{ code: "PRY", en: "Paraguay", zh: "巴拉圭" },
	{ code: "PER", en: "Peru", zh: "秘鲁" },
	{ code: "PHL", en: "Philippines", zh: "菲律宾" },
	{ code: "POL", en: "Poland", zh: "波兰" },
	{ code: "PRT", en: "Portugal", zh: "葡萄牙" },
	{ code: "PRI", en: "Puerto Rico", zh: "波多黎各" },
	{ code: "QAT", en: "Qatar", zh: "卡塔尔" },
	{ code: "REU", en: "Réunion", zh: "留尼汪" },
	{ code: "ROU", en: "Romania", zh: "罗马尼亚" },
	{ code: "RUS", en: "Russia", zh: "俄罗斯" },
	{ code: "RWA", en: "Rwanda", zh: "卢旺达" },
	{ code: "WSM", en: "Samoa", zh: "萨摩亚" },
	{ code: "SMR", en: "San Marino", zh: "圣马力诺" },
	{ code: "STP", en: "São Tomé & Príncipe", zh: "圣多美和普林西比" },
	{ code: "SAU", en: "Saudi Arabia", zh: "沙特阿拉伯" },
	{ code: "SEN", en: "Senegal", zh: "塞内加尔" },
	{ code: "SRB", en: "Serbia", zh: "塞尔维亚" },
	{ code: "SYC", en: "Seychelles", zh: "塞舌尔" },
	{ code: "SLE", en: "Sierra Leone", zh: "塞拉利昂" },
	{ code: "SGP", en: "Singapore", zh: "新加坡" },
	{ code: "SXM", en: "Sint Maarten", zh: "荷属圣马丁" },
	{ code: "SVK", en: "Slovakia", zh: "斯洛伐克" },
	{ code: "SVN", en: "Slovenia", zh: "斯洛文尼亚" },
	{ code: "SLB", en: "Solomon Islands", zh: "所罗门群岛" },
	{ code: "SOM", en: "Somalia", zh: "索马里" },
	{ code: "ZAF", en: "South Africa", zh: "南非" },
	{ code: "KOR", en: "South Korea", zh: "韩国" },
	{ code: "SSD", en: "South Sudan", zh: "南苏丹" },
	{ code: "ESP", en: "Spain", zh: "西班牙" },
	{ code: "LKA", en: "Sri Lanka", zh: "斯里兰卡" },
	{ code: "SHN", en: "St. Helena", zh: "圣赫勒拿" },
	{ code: "KNA", en: "St. Kitts & Nevis", zh: "圣基茨和尼维斯" },
	{ code: "LCA", en: "St. Lucia", zh: "圣卢西亚" },
	{ code: "SPM", en: "St. Pierre & Miquelon", zh: "圣皮埃尔和密克隆群岛" },
	{ code: "VCT", en: "St. Vincent & Grenadines", zh: "圣文森特和格林纳丁斯" },
	{ code: "SUR", en: "Suriname", zh: "苏里南" },
	{ code: "SWE", en: "Sweden", zh: "瑞典" },
	{ code: "CHE", en: "Switzerland", zh: "瑞士" },
	{ code: "TWN", en: "Taiwan", zh: "台湾" },
	{ code: "TJK", en: "Tajikistan", zh: "塔吉克斯坦" },
	{ code: "TZA", en: "Tanzania", zh: "坦桑尼亚" },
	{ code: "THA", en: "Thailand", zh: "泰国" },
	{ code: "TLS", en: "Timor-Leste", zh: "东帝汶" },
	{ code: "TGO", en: "Togo", zh: "多哥" },
	{ code: "TON", en: "Tonga", zh: "汤加" },
	{ code: "TTO", en: "Trinidad & Tobago", zh: "特立尼达和多巴哥" },
	{ code: "TUN", en: "Tunisia", zh: "突尼斯" },
	{ code: "TUR", en: "Türkiye", zh: "土耳其" },
	{ code: "TKM", en: "Turkmenistan", zh: "土库曼斯坦" },
	{ code: "TCA", en: "Turks & Caicos Islands", zh: "特克斯和凯科斯群岛" },
	{ code: "TUV", en: "Tuvalu", zh: "图瓦卢" },
	{ code: "UMI", en: "U.S. Outlying Islands", zh: "美国本土外小岛屿" },
	{ code: "VIR", en: "U.S. Virgin Islands", zh: "美属维尔京群岛" },
	{ code: "UGA", en: "Uganda", zh: "乌干达" },
	{ code: "UKR", en: "Ukraine", zh: "乌克兰" },
	{ code: "ARE", en: "United Arab Emirates", zh: "阿拉伯联合酋长国" },
	{ code: "ARE", en: "United Arab Emirates", zh: "阿拉伯联合酋长国" },
	{ code: "GBR", en: "United Kingdom", zh: "英国" },
	{ code: "USA", en: "United States", zh: "美国" },
	{ code: "URY", en: "Uruguay", zh: "乌拉圭" },
	{ code: "UZB", en: "Uzbekistan", zh: "乌兹别克斯坦" },
	{ code: "VUT", en: "Vanuatu", zh: "瓦努阿图" },
	{ code: "VAT", en: "Vatican City", zh: "梵蒂冈" },
	{ code: "VEN", en: "Venezuela", zh: "委内瑞拉" },
	{ code: "VNM", en: "Vietnam", zh: "越南" },
	{ code: "WLF", en: "Wallis & Futuna", zh: "瓦利斯和富图纳" },
	{ code: "YEM", en: "Yemen", zh: "也门" },
	{ code: "ZMB", en: "Zambia", zh: "赞比亚" },
	{ code: "ZWE", en: "Zimbabwe", zh: "津巴布韦" },
];

// Apple TerritoryCode 源数据有重复条目（如 ARE）——按 code 去重，避免列表渲染 key 冲突。
export const STOREFRONTS: readonly Storefront[] = [
	...new Map(ALL_STOREFRONTS.map((s) => [s.code, s])).values(),
];

const BY_CODE = new Map(STOREFRONTS.map((s) => [s.code, s]));

/** 取 storefront 代码的本地化名称；未知代码原样返回，空值返回 "—"。 */
export function storefrontName(code: string | null | undefined, locale: string): string {
	if (!code) return "—";
	const s = BY_CODE.get(code);
	if (!s) return code;
	return locale === "zh-Hans" ? s.zh : s.en;
}
